import Head from 'next/head'
import ProductList from '../components/productList'

export default function Home({ products }) {

  return (
    <div>
      <Head>
        <title>Next E-Commerce</title>
        <meta name="description" content="A sample e-commerce app generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <ProductList products={products}></ProductList>

    </div>
  )
}

export const getStaticProps = async () => {
  const res = await fetch('https://fakestoreapi.com/products');
  const products = await res.json();

  return {
    props: {
      products
    }
  }
}
